package fyneloader

// Key constants define the JSON/YAML syntax that the loader accepts.
const (
	KeyAlign       = "align"
	KeyChild       = "child"
	KeyChildren    = "children"
	KeyDisabled    = "disabled"
	KeyFunc        = "func"
	KeyHidden      = "hidden"
	KeyIconPlace   = "icon-placement"
	KeyImageFill   = "image-fill"
	KeyImagePath   = "image-path"
	KeyImageURI    = "image-uri"
	KeyImportance  = "importance"
	KeyItems       = "items"
	KeyMax         = "max"
	KeyMin         = "min"
	KeyMultiOpen   = "multi-open"
	KeyOpen        = "open"
	KeyOptions     = "options"
	KeyOrientation = "orientation"
	KeyRequired    = "required"
	KeySelected    = "selected"
	KeyStep        = "step"
	KeyStyle       = "style"
	KeySubTitle    = "subtitle"
	KeyText        = "text"
	KeyTitle       = "title"
	KeyType        = "type"
	KeyWrap        = "wrap"
)

// Value constants define constant values that the loader accepts.
const (
	ValueBreak      = "break"
	ValueCenter     = "center"
	ValueContain    = "contain"
	ValueDefault    = "default"
	ValueHigh       = "high"
	ValueHorizontal = "horizontal"
	ValueLeading    = "leading"
	ValueLow        = "low"
	ValueMedium     = "medium"
	ValueOff        = "off"
	ValueOriginal   = "original"
	ValueStretch    = "stretch"
	ValueTrailing   = "trailing"
	ValueTruncate   = "truncate"
	ValueVertical   = "vertical"
	ValueWord       = "word"
)
